spring.application.name=SpringOauth2Client

#Configuraciones varías

#Configuraciones de seguridad - para hacer pruebas sin 'BD'
spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}
spring.security.user.roles=${ROLE}

#Configuraciones de Autenticación OAuth usando 'GitHub'
spring.security.oauth2.client.registration.github.client-id=${GH_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GH_CLIENT_SECRET}

#Configuraciones de Autenticación OAuth usando 'Google'
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
